// Mobilier, décoration, objets domestiques, jardin, animaux.
//
// Fourre-tout assumé : ce sont les objets que l'on montre à une webcam sans y
// penser. Beaucoup n'ouvrent qu'une ou deux affordances, mais la règle du projet
// est qu'aucun objet réel ne doit renvoyer « inconnu » — c'est ce moment-là qui
// casse l'illusion.

export const MAISON = {
  'chaise':            { a: 'une', p: ['rigide', 'lourd', 'inflammable'] },
  'tabouret':          { a: 'un',  p: ['rigide', 'lourd', 'inflammable'] },
  'table':             { a: 'une', p: ['plat', 'rigide', 'lourd', 'inflammable'] },
  'coussin':           { a: 'un',  p: ['souple', 'absorbant', 'inflammable', 'leger'] },
  'rideau':            { a: 'un',  p: ['souple', 'plat', 'allonge', 'inflammable', 'absorbant'] },
  'tapis':             { a: 'un',  p: ['souple', 'plat', 'absorbant', 'inflammable', 'lourd'] },
  'cintre':            { a: 'un',  p: ['rigide', 'souple', 'allonge', 'mince', 'conducteur', 'magnetique', 'leger', 'tenable_une_main'] },
  'vase':              { a: 'un',  p: ['creux', 'cassant', 'lourd', 'contient_liquide'] },
  'pot de fleurs':     { a: 'un',  p: ['creux', 'rigide', 'cassant', 'lourd', 'tenable_une_main'] },
  'plante':            { a: 'une', p: ['souple', 'inflammable', 'odorant'] },
  'fleur':             { a: 'une', p: ['souple', 'allonge', 'mince', 'odorant', 'inflammable', 'leger', 'tenable_une_main'] },
  'bougeoir':          { a: 'un',  p: ['rigide', 'lourd', 'conducteur', 'reflechissant', 'tenable_une_main'] },
  'cadre photo':       { a: 'un',  p: ['plat', 'rigide', 'cassant', 'reflechissant', 'tenable_une_main'] },
  'poubelle':          { a: 'une', p: ['creux', 'rigide', 'odorant'] },
  'boîte en carton':   { a: 'une', p: ['creux', 'rigide', 'inflammable', 'porte_texte', 'leger'] },
  'valise':            { a: 'une', p: ['creux', 'rigide', 'lourd'] },
  'panier':            { a: 'un',  p: ['creux', 'rigide', 'inflammable', 'leger', 'tenable_une_main'] },
  'clé de maison':     { a: 'une', p: ['rigide', 'mince', 'plat', 'conducteur', 'magnetique', 'leger', 'tenable_une_main'] },
  'porte-clés':        { a: 'un',  p: ['rigide', 'creux', 'conducteur', 'magnetique', 'leger', 'tenable_une_main'] },
  'interrupteur':      { a: 'un',  p: ['plat', 'rigide', 'conducteur', 'leger'] },
  'prise électrique':  { a: 'une', p: ['plat', 'rigide', 'conducteur', 'creux'] },
  'ampoule de bureau': { a: 'une', p: ['cassant', 'creux', 'conducteur', 'emet_lumiere', 'leger', 'tenable_une_main'] },
  'radiateur':         { a: 'un',  p: ['rigide', 'lourd', 'conducteur', 'magnetique'] },
  'aspirateur':        { a: 'un',  p: ['rigide', 'lourd', 'electronique', 'emet_son', 'creux'] },
  'fer à repasser':    { a: 'un',  p: ['rigide', 'lourd', 'plat', 'electronique', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'planche à repasser': { a: 'une', p: ['plat', 'rigide', 'allonge', 'lourd'] },
  'réfrigérateur':     { a: 'un',  p: ['creux', 'rigide', 'lourd', 'electronique', 'magnetique', 'isolant_thermique'] },
  'four':              { a: 'un',  p: ['creux', 'rigide', 'lourd', 'electronique', 'conducteur', 'emet_son'] },
  'machine à laver':   { a: 'une', p: ['creux', 'rigide', 'lourd', 'electronique', 'contient_liquide', 'emet_son'] },
  'escabeau':          { a: 'un',  p: ['rigide', 'lourd', 'conducteur'] },
  'arrosoir':          { a: 'un',  p: ['creux', 'rigide', 'contient_liquide', 'tenable_une_main'] },
  'râteau':            { a: 'un',  p: ['pointu', 'rigide', 'allonge', 'conducteur'] },
  'pelle':             { a: 'une', p: ['plat', 'rigide', 'allonge', 'conducteur', 'magnetique'] },
  'sécateur de jardin': { a: 'un', p: ['tranchant', 'pointu', 'rigide', 'conducteur', 'tenable_une_main'] },
  'tuyau d\'arrosage': { a: 'un',  p: ['souple', 'creux', 'allonge', 'contient_liquide'] },
  'gravier':           { a: 'du',  p: ['rigide', 'lourd'] },
  'caillou':           { a: 'un',  p: ['rigide', 'lourd', 'tenable_une_main'] },
  'brique':            { a: 'une', p: ['rigide', 'lourd', 'cassant', 'tenable_une_main'] },
  'planche de bois':   { a: 'une', p: ['plat', 'rigide', 'allonge', 'inflammable', 'lourd'] },
  'bâton':             { a: 'un',  p: ['rigide', 'allonge', 'inflammable', 'appetissant_animal', 'tenable_une_main'] },
  'laisse':            { a: 'une', p: ['souple', 'allonge', 'inflammable', 'tenable_une_main'] },
  'gamelle':           { a: 'une', p: ['creux', 'rigide', 'conducteur', 'tenable_une_main'] },
  'jouet pour chien':  { a: 'un',  p: ['souple', 'appetissant_animal', 'emet_son', 'odorant', 'leger', 'tenable_une_main'] },
  'litière':           { a: 'de la', p: ['absorbant', 'odorant', 'lourd'] },
  'cage':              { a: 'une', p: ['creux', 'rigide', 'conducteur', 'magnetique', 'lourd'] },
  'chat':              { a: 'un',  p: ['souple', 'emet_son', 'odorant', 'lourd'] },
  'chien':             { a: 'un',  p: ['souple', 'emet_son', 'odorant', 'lourd'] },
  'personne':          { a: 'une', p: ['souple', 'emet_son', 'lourd'] },
};
