// Aliments et boissons.
//
// `comestible` et `appetissant_animal` ne se recouvrent pas : le chocolat est
// comestible pour l'humain et toxique pour le chien, l'os cru est l'inverse.
// Cette asymétrie n'est pas un détail de réalisme, c'est un ressort d'énigme :
// certains aliments nourrissent le joueur, d'autres seulement le gardien.

export const NOURRITURE = {
  'pomme':            { a: 'une', p: ['rigide', 'comestible', 'appetissant_animal', 'odorant', 'leger', 'tenable_une_main'] },
  'banane':           { a: 'une', p: ['souple', 'allonge', 'comestible', 'appetissant_animal', 'odorant', 'leger', 'tenable_une_main'] },
  'orange':           { a: 'une', p: ['rigide', 'comestible', 'odorant', 'leger', 'tenable_une_main'] },
  'citron':           { a: 'un',  p: ['rigide', 'comestible', 'odorant', 'contient_liquide', 'conducteur', 'leger', 'tenable_une_main'] },
  'poire':            { a: 'une', p: ['rigide', 'comestible', 'appetissant_animal', 'odorant', 'leger', 'tenable_une_main'] },
  'fraise':           { a: 'une', p: ['souple', 'comestible', 'odorant', 'leger'] },
  'raisin':           { a: 'du',  p: ['souple', 'comestible', 'odorant', 'leger'] },
  'tomate':           { a: 'une', p: ['souple', 'comestible', 'odorant', 'contient_liquide', 'leger', 'tenable_une_main'] },
  'carotte':          { a: 'une', p: ['rigide', 'allonge', 'comestible', 'appetissant_animal', 'leger', 'tenable_une_main'] },
  'pomme de terre':   { a: 'une', p: ['rigide', 'comestible', 'lourd', 'tenable_une_main'] },
  'oignon':           { a: 'un',  p: ['rigide', 'comestible', 'odorant', 'tenable_une_main'] },
  'ail':              { a: 'de l\'', p: ['rigide', 'comestible', 'odorant', 'leger', 'tenable_une_main'] },
  'salade':           { a: 'de la', p: ['souple', 'comestible', 'leger'] },
  'brocoli':          { a: 'un',  p: ['rigide', 'comestible', 'odorant', 'leger', 'tenable_une_main'] },
  'concombre':        { a: 'un',  p: ['rigide', 'allonge', 'comestible', 'contient_liquide', 'tenable_une_main'] },
  'pain':             { a: 'du',  p: ['souple', 'allonge', 'comestible', 'appetissant_animal', 'odorant', 'inflammable', 'absorbant', 'tenable_une_main'] },
  'baguette':         { a: 'une', p: ['rigide', 'allonge', 'comestible', 'appetissant_animal', 'odorant', 'inflammable', 'tenable_une_main'] },
  'sandwich':         { a: 'un',  p: ['souple', 'comestible', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'croissant':        { a: 'un',  p: ['souple', 'comestible', 'appetissant_animal', 'odorant', 'inflammable', 'leger', 'tenable_une_main'] },
  'biscuit':          { a: 'un',  p: ['rigide', 'cassant', 'comestible', 'appetissant_animal', 'odorant', 'leger', 'tenable_une_main'] },
  'gâteau':           { a: 'un',  p: ['souple', 'comestible', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'chocolat':         { a: 'du',  p: ['rigide', 'cassant', 'plat', 'comestible', 'odorant', 'leger', 'tenable_une_main'] },
  'bonbon':           { a: 'un',  p: ['rigide', 'comestible', 'odorant', 'leger', 'tenable_une_main'] },
  'pizza':            { a: 'une', p: ['plat', 'souple', 'comestible', 'appetissant_animal', 'odorant'] },
  'hot-dog':          { a: 'un',  p: ['souple', 'allonge', 'comestible', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'hamburger':        { a: 'un',  p: ['souple', 'comestible', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'saucisse':         { a: 'une', p: ['souple', 'allonge', 'comestible', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'jambon':           { a: 'du',  p: ['souple', 'plat', 'comestible', 'appetissant_animal', 'odorant', 'leger'] },
  'viande':           { a: 'de la', p: ['souple', 'comestible', 'appetissant_animal', 'odorant'] },
  'poisson':          { a: 'un',  p: ['souple', 'allonge', 'comestible', 'appetissant_animal', 'odorant'] },
  'os':               { a: 'un',  p: ['rigide', 'allonge', 'cassant', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'fromage':          { a: 'du',  p: ['souple', 'comestible', 'appetissant_animal', 'odorant', 'tenable_une_main'] },
  'œuf':              { a: 'un',  p: ['rigide', 'cassant', 'creux', 'comestible', 'leger', 'tenable_une_main'] },
  'yaourt':           { a: 'un',  p: ['creux', 'souple', 'comestible', 'contient_liquide', 'leger', 'tenable_une_main'] },
  'lait':             { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant'] },
  'café':             { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant'] },
  'thé':              { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant'] },
  'jus de fruit':     { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant'] },
  'eau':              { a: 'de l\'', p: ['contient_liquide', 'comestible'] },
  'soda':             { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant'] },
  'vin':              { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant', 'inflammable'] },
  'bière':            { a: 'de la', p: ['contient_liquide', 'comestible', 'odorant'] },
  'alcool à brûler':  { a: 'de l\'', p: ['contient_liquide', 'odorant', 'inflammable'] },
  'huile':            { a: 'de l\'', p: ['contient_liquide', 'comestible', 'inflammable', 'odorant'] },
  'vinaigre':         { a: 'du',  p: ['contient_liquide', 'comestible', 'odorant', 'conducteur'] },
  'sel':              { a: 'du',  p: ['comestible', 'leger', 'conducteur'] },
  'sucre':            { a: 'du',  p: ['comestible', 'appetissant_animal', 'inflammable', 'leger'] },
  'farine':           { a: 'de la', p: ['comestible', 'inflammable', 'leger'] },
  'croquettes':       { a: 'des', p: ['rigide', 'appetissant_animal', 'odorant', 'leger'] },
  'noix':             { a: 'une', p: ['rigide', 'cassant', 'comestible', 'leger', 'tenable_une_main'] },
};
