// Outillage, quincaillerie, matériel d'atelier.
//
// La catégorie la plus dense en affordances : c'est ici que se trouvent la
// plupart des objets « qui servent à quelque chose » au sens du jeu. Elle est
// donc aussi celle où une erreur de propriété se voit le plus vite.
//
// Rappel du format : { a: article, p: [propriétés], syn: [autres noms] }
// Voir base/index.js pour le contrat complet.

export const OUTILS = {
  'couteau':            { a: 'un',  p: ['tranchant', 'pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'tenable_une_main', 'leger'] },
  'cutter':             { a: 'un',  p: ['tranchant', 'pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'tenable_une_main', 'leger'], syn: ['couteau à lames', 'exacto'] },
  'ciseaux':            { a: 'des', p: ['tranchant', 'pointu', 'rigide', 'mince', 'conducteur', 'tenable_une_main', 'leger'] },
  'sécateur':           { a: 'un',  p: ['tranchant', 'pointu', 'rigide', 'conducteur', 'tenable_une_main'] },
  'scie':               { a: 'une', p: ['tranchant', 'rigide', 'allonge', 'mince', 'conducteur', 'tenable_une_main', 'emet_son'] },
  'lame de rasoir':     { a: 'une', p: ['tranchant', 'mince', 'plat', 'rigide', 'conducteur', 'tenable_une_main', 'leger'] },
  'tournevis':          { a: 'un',  p: ['pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'tenable_une_main'] },
  'tournevis cruciforme': { a: 'un', p: ['pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'tenable_une_main'] },
  'clé plate':          { a: 'une', p: ['rigide', 'allonge', 'plat', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'clé à molette':      { a: 'une', p: ['rigide', 'allonge', 'lourd', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'pince':              { a: 'une', p: ['rigide', 'allonge', 'pointu', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'pince coupante':     { a: 'une', p: ['tranchant', 'rigide', 'allonge', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'marteau':            { a: 'un',  p: ['rigide', 'lourd', 'allonge', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'masse':              { a: 'une', p: ['rigide', 'lourd', 'allonge'] },
  'burin':              { a: 'un',  p: ['tranchant', 'rigide', 'allonge', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'pied-de-biche':      { a: 'un',  p: ['rigide', 'allonge', 'lourd', 'mince', 'conducteur', 'magnetique'], syn: ['levier', 'barre à mine'] },
  'perceuse':           { a: 'une', p: ['rigide', 'lourd', 'electronique', 'alimente', 'emet_son', 'tenable_une_main'] },
  'foret':              { a: 'un',  p: ['pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'magnetique', 'leger'], syn: ['mèche'] },
  'lime':               { a: 'une', p: ['rigide', 'allonge', 'mince', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'râpe à métaux':      { a: 'une', p: ['rigide', 'allonge', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'clou':               { a: 'un',  p: ['pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'magnetique', 'leger'] },
  'vis':                { a: 'une', p: ['pointu', 'rigide', 'allonge', 'mince', 'conducteur', 'magnetique', 'leger'] },
  'écrou':              { a: 'un',  p: ['rigide', 'creux', 'conducteur', 'magnetique', 'leger'] },
  'boulon':             { a: 'un',  p: ['rigide', 'allonge', 'conducteur', 'magnetique', 'leger'] },
  'trombone':           { a: 'un',  p: ['souple', 'mince', 'allonge', 'conducteur', 'magnetique', 'leger', 'tenable_une_main'] },
  'épingle':            { a: 'une', p: ['pointu', 'mince', 'allonge', 'rigide', 'conducteur', 'magnetique', 'leger'] },
  'épingle à cheveux':  { a: 'une', p: ['pointu', 'mince', 'allonge', 'souple', 'conducteur', 'magnetique', 'leger'], syn: ['pince à cheveux', 'barrette'] },
  'aiguille':           { a: 'une', p: ['pointu', 'mince', 'allonge', 'rigide', 'conducteur', 'magnetique', 'leger'] },
  'fil de fer':         { a: 'du',  p: ['souple', 'mince', 'allonge', 'conducteur', 'magnetique', 'leger'] },
  'corde':              { a: 'une', p: ['souple', 'allonge', 'inflammable', 'absorbant'] },
  'ficelle':            { a: 'de la', p: ['souple', 'allonge', 'mince', 'inflammable', 'leger'] },
  'chaîne':             { a: 'une', p: ['souple', 'allonge', 'lourd', 'conducteur', 'magnetique'] },
  'ruban adhésif':      { a: 'du',  p: ['souple', 'mince', 'inflammable', 'leger'], syn: ['scotch', 'adhésif'] },
  'mètre ruban':        { a: 'un',  p: ['souple', 'mince', 'allonge', 'porte_texte', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'règle':              { a: 'une', p: ['rigide', 'plat', 'allonge', 'mince', 'porte_texte', 'leger', 'tenable_une_main'] },
  'niveau à bulle':     { a: 'un',  p: ['rigide', 'allonge', 'contient_liquide', 'porte_texte', 'tenable_une_main'] },
  'lampe torche':       { a: 'une', p: ['rigide', 'allonge', 'electronique', 'alimente', 'emet_lumiere', 'tenable_une_main'], syn: ['lampe de poche', 'torche'] },
  'briquet':            { a: 'un',  p: ['rigide', 'leger', 'inflammable', 'emet_lumiere', 'tenable_une_main', 'contient_liquide'] },
  'allumette':          { a: 'une', p: ['rigide', 'mince', 'allonge', 'inflammable', 'emet_lumiere', 'leger'] },
  'bougie':             { a: 'une', p: ['rigide', 'allonge', 'inflammable', 'emet_lumiere', 'odorant', 'tenable_une_main'] },
  'extincteur':         { a: 'un',  p: ['rigide', 'lourd', 'creux', 'porte_texte', 'emet_son'] },
  'aimant':             { a: 'un',  p: ['rigide', 'lourd', 'magnetique', 'conducteur', 'tenable_une_main', 'leger'] },
  'pile':               { a: 'une', p: ['rigide', 'creux', 'alimente', 'conducteur', 'porte_texte', 'leger', 'tenable_une_main'] },
  'batterie externe':   { a: 'une', p: ['rigide', 'plat', 'electronique', 'alimente', 'porte_texte', 'tenable_une_main'], syn: ['powerbank'] },
  'câble électrique':   { a: 'un',  p: ['souple', 'allonge', 'mince', 'conducteur', 'inflammable'], syn: ['fil électrique'] },
  'rallonge':           { a: 'une', p: ['souple', 'allonge', 'conducteur', 'inflammable'] },
  'gants de travail':   { a: 'des', p: ['souple', 'absorbant', 'isolant_thermique', 'inflammable', 'leger'] },
  'casque de chantier': { a: 'un',  p: ['rigide', 'creux', 'leger', 'isolant_thermique'] },
  'lunettes de protection': { a: 'des', p: ['rigide', 'plat', 'reflechissant', 'leger', 'tenable_une_main'] },
  'échelle':            { a: 'une', p: ['rigide', 'allonge', 'lourd', 'conducteur'] },
  'seau':               { a: 'un',  p: ['creux', 'rigide', 'contient_liquide', 'tenable_une_main'] },
  'entonnoir':          { a: 'un',  p: ['creux', 'rigide', 'leger', 'tenable_une_main'] },
  'tuyau':              { a: 'un',  p: ['souple', 'creux', 'allonge', 'contient_liquide'] },
  'cadenas':            { a: 'un',  p: ['rigide', 'lourd', 'conducteur', 'magnetique', 'tenable_une_main'] },
  'clé':                { a: 'une', p: ['rigide', 'mince', 'plat', 'allonge', 'conducteur', 'magnetique', 'leger', 'tenable_une_main'] },
  'boussole':           { a: 'une', p: ['rigide', 'plat', 'magnetique', 'porte_texte', 'leger', 'tenable_une_main'] },
  'loupe':              { a: 'une', p: ['rigide', 'plat', 'reflechissant', 'cassant', 'leger', 'tenable_une_main'] },
  'miroir':             { a: 'un',  p: ['plat', 'rigide', 'cassant', 'reflechissant', 'tenable_une_main'] },
  'ampoule':            { a: 'une', p: ['cassant', 'creux', 'conducteur', 'emet_lumiere', 'leger', 'tenable_une_main'] },
};
